Update ts-ci

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -2,36 +2,60 @@ name: ci
 on:
   push:
     branches:
-      - develop
+      - main
   pull_request:
     branches:
-      - develop
+      - main
 
 jobs:
 
-  test_node:
+  test_lint:
     runs-on: ubuntu-latest
-    if: ${{ !github.event.created }}
+    if: ${{ !github.event.created && github.repository != 'garronej/denoify_ci' }}
+    steps:
+    - uses: actions/checkout@v2.3.4
+    - uses: actions/setup-node@v2.1.3
+    - uses: bahmutov/npm-install@v1
+    - name: If this step fails run 'npm run lint' and 'npm run format' then commit again.
+      run: |
+        PACKAGE_MANAGER=npm
+        if [ -f "./yarn.lock" ]; then
+            PACKAGE_MANAGER=yarn
+        fi
+        $PACKAGE_MANAGER run lint:check
+        $PACKAGE_MANAGER run format:check
+  test_node:
+    runs-on: ${{ matrix.os }}
+    needs: test_lint
     strategy:
       matrix:
-        node: [ '14', '13', '12', '11', '10', '8' ]
-    name: Test with Node v${{ matrix.node }}
+        node: [ '15', '14', '12' ]
+        os: [ windows-latest, ubuntu-latest ]
+    name: Test with Node v${{ matrix.node }} on ${{ matrix.os }}
     steps:
-
-    - uses: actions/checkout@v2
-    - uses: actions/setup-node@v1
+    - name: Tell if project is using npm or yarn
+      id: step1
+      uses: garronej/ts-ci@v1.1.2
+      with: 
+        action_name: tell_if_project_uses_npm_or_yarn
+    - uses: actions/checkout@v2.3.4
+    - uses: actions/setup-node@v2.1.3
       with:
         node-version: ${{ matrix.node }}
-    - run: npm ci
-    - run: npx tsc
-    - run: npm run test:node
-
+    - uses: bahmutov/npm-install@v1
+    - if: steps.step1.outputs.npm_or_yarn == 'yarn'
+      run: |
+        yarn build
+        yarn test:node
+    - if: steps.step1.outputs.npm_or_yarn == 'npm'
+      run: |
+        npm run build
+        npm test:node
   test_deno:
     runs-on: ubuntu-latest
-    if: ${{ !github.event.created }}
+    needs: test_lint
     name: test with Deno
     steps: 
-
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v1
     - name: Cache
@@ -46,57 +70,105 @@ jobs:
     - uses: denolib/setup-deno@master
       with:
         deno-version: v1.x
-    - run: npm ci
-    - run: npm run build
-    - run: npm run test:deno
+    - run: deno --version
+    - uses: bahmutov/npm-install@v1
+    - run: |
+        PACKAGE_MANAGER=npm
+        if [ -f "./yarn.lock" ]; then
+            PACKAGE_MANAGER=yarn
+        fi
+        $PACKAGE_MANAGER run build
+        $PACKAGE_MANAGER run test:deno
 
-  trigger_publish:
-    name: Trigger publish.yaml workflow if package.json version updated ( and secrets.PAT is set ).
+  check_if_version_upgraded:
+    name: Check if version upgrade
+    # We run this only if it's a push on the default branch or if it's a PR from a 
+    # branch (meaning not a PR from a fork). It would be more straightforward to test if secrets.NPM_TOKEN is 
+    # defined but GitHub Action don't allow it yet.
+    if: |
+      github.event_name == 'push' || 
+      github.event.pull_request.head.repo.owner.login == github.event.pull_request.base.repo.owner.login 
     runs-on: ubuntu-latest
-    env:
-      PAT: ${{secrets.PAT}}
-    if: github.event_name == 'push' && github.event.head_commit.author.name != 'denoify_ci'
-    needs:
+    needs: 
       - test_node
       - test_deno
+    outputs:
+      from_version: ${{ steps.step1.outputs.from_version }}
+      to_version: ${{ steps.step1.outputs.to_version }}
+      is_upgraded_version: ${{ steps.step1.outputs.is_upgraded_version }}
+      is_release_beta: ${{steps.step1.outputs.is_release_beta }}
     steps:
-
-    - name: Get version on latest
-      id: v_latest
-      uses: garronej/github_actions_toolkit@v1.4
+    - uses: garronej/ts-ci@v1.1.2
+      id: step1
       with: 
-        action_name: get_package_json_version
-        owner: ${{github.repository_owner}}
-        repo: ${{github.event.repository.name}}
-        branch: latest
-        compare_to_version: '0.0.0'
+        action_name: is_package_json_version_upgraded
+        branch: ${{ github.head_ref || github.ref }}
 
-    - name: Get version on develop
-      id: v_develop
-      uses: garronej/github_actions_toolkit@v1.4
-      with: 
-        action_name: get_package_json_version
-        owner: ${{github.repository_owner}}
-        repo: ${{github.event.repository.name}}
-        branch: ${{ github.sha }}
-        compare_to_version: ${{steps.v_latest.outputs.version || '0.0.0'}}
-
-    - name: 'Trigger the ''publish'' workflow' 
-      if: ${{ !!env.PAT && steps.v_develop.outputs.compare_result == '1' }}
-      uses: garronej/github_actions_toolkit@v1.4
-      env:
-        GITHUB_TOKEN: ${{ secrets.PAT }} 
+  publish:
+    runs-on: ubuntu-latest
+    needs: 
+      - check_if_version_upgraded
+    # We create a release only if the version have been upgraded and we are on a default branch
+    # PR on the default branch can release beta but not real release
+    if: |
+      needs.check_if_version_upgraded.outputs.is_upgraded_version == 'true' &&
+      (
+        github.event_name == 'push' ||
+        needs.check_if_version_upgraded.outputs.is_release_beta == 'true'
+      )
+    steps:
+    - uses: actions/checkout@v2
       with:
-        action_name: dispatch_event
-        owner: ${{github.repository_owner}}
-        repo: ${{github.event.repository.name}}
-        event_type: publish
-        client_payload_json: |
-          ${{
-            format(
-              '{{"from_version":"{0}","to_version":"{1}","repo":"{2}"}}',
-              steps.v_latest.outputs.version,
-              steps.v_develop.outputs.version,
-              github.event.repository.name
-            )
-          }}
+        fetch-depth: 0
+        ref: ${{ github.ref }}
+    - run: rm -r .github
+    - run: |
+        git branch -d latest || true
+        git push origin :latest || true
+    - run: |
+        git branch latest
+        git checkout latest
+    - uses: actions/setup-node@v2.1.3
+      with:
+        node-version: '15'
+        registry-url: https://registry.npmjs.org/
+    - uses: bahmutov/npm-install@v1
+    - run: |
+        PACKAGE_MANAGER=npm
+        if [ -f "./yarn.lock" ]; then
+            PACKAGE_MANAGER=yarn
+        fi
+        $PACKAGE_MANAGER run build
+    - run: npx -y -p denoify@0.6.5 denoify_enable_short_npm_import_path
+      env:
+        DRY_RUN: "0"
+    - run: |
+        if [ "$(npm show . version)" = "$VERSION" ]; then
+          echo "This version is already published"
+          exit 0
+        fi
+        if [ "$NODE_AUTH_TOKEN" = "" ]; then
+          echo "Can't publish on NPM, You must first create a secret called NPM_TOKEN that contains your NPM auth token. https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets"
+          false
+        fi
+        npm publish
+      env:
+        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
+        VERSION: ${{ needs.check_if_version_upgraded.outputs.to_version }}
+    - run: |
+        git config --global user.name "actions"
+        git config --global user.email actions@example.com
+        git add -A
+        git commit -am "Enabling shorter import paths"
+        git push origin latest
+    - uses: softprops/action-gh-release@v1
+      with:
+        name: Release v${{ needs.check_if_version_upgraded.outputs.to_version }}
+        tag_name: v${{ needs.check_if_version_upgraded.outputs.to_version }}
+        target_commitish: latest
+        generate_release_notes: true
+        draft: false
+        prerelease: ${{ needs.check_if_version_upgraded.outputs.is_release_beta == 'true' }}
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
+
